version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-financial-anomaly
    ports:
      - "3000:3000"
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=eda-fin-anomaly-ds,eda-anomaly-heatmap-panel
      - GF_LOG_LEVEL=debug
      - GF_USERS_DEFAULT_THEME=dark
    volumes:
      - ./dist:/var/lib/grafana/plugins/eda-fin-anomaly-ds
      - ../grafana-anomaly-heatmap-panel/dist:/var/lib/grafana/plugins/eda-anomaly-heatmap-panel
      - grafana-storage:/var/lib/grafana
    networks:
      - grafana-network

volumes:
  grafana-storage:
    driver: local

networks:
  grafana-network:
    driver: bridge
